### ISSUE TITLE
missing fields

### ISSUE THREAD

**Issue by jcm** [iMenlo/system_pay#1]
Hi,

Thks for this gem to handle credit card payment by system_pay.
Do you intend to add missing fields documented in 2.2 Guide?
For instance, vads_cust_phone, vads_cust_city, vads_cust_title...

Same for return values : all return codes could be entered.
I'm working on it (because I need to have this), I will commit to my fork. Tell me wether you wish to mix it.

**Comment by Sylvain** [comment]
Hi ! 

Yes, the gem need to have all the potential values, it was a quick gem to handle my particular need. But if you need other fields and values, feel free and I'll do the merge with great pleasure ! 

Kind regards, 

Sylvain
